### ISSUE TITLE
pretrained file

### ISSUE THREAD

**Issue by Cxx96** [peymanbateni/simple-cnaps#2]
Hello, when I decompressed the pretrained file package, the compressed file was damaged. If it is convenient for you, could you please send it again? Thank you very much!!

**Comment by peymanbateni** [comment]
Hi there, apologies for the late-reply! I have double checked both the ResNet18 checkpoint and Simple CNAPS checkpoints and they work fine. Could it be that they were damaged during download/cloning?

Alternatively, feel free to email me at pbateni@cs.ubc.ca, and I can try providing you with a specific Google drive link (which will be released publicly later)!

**Comment by peymanbateni** [comment]
Hi there, I have triple checked all checkpoints (since I suspect maybe there might a GPU mismatch problem), but they are all fine. What I suspect is that if you using the download as zip feature of github, the compression procedure is corrupting the saved checkpoint to the degree that it is not recoverable. This has an easy fix which is cloning the repo instead. That said, if that's not possible I can tar the repo without compression and make it available on Google for you to download.

Please let me know. Again, I am much better with replying on email so feel free to reach out to me there for the link to the uncompressed saved repository.

Thanks for your interest in our works!
